name: Updating Version

on: [workflow_dispatch]

jobs:
  build:
    name: Updating Version
    runs-on: ubuntu-latest

    outputs:
      output1: ${{ steps.pl.outputs.new-version-1 }}
      output2: ${{ steps.pl.outputs.new-version-2 }}
      output3: ${{ steps.pl.outputs.new-version-3 }}
      output4: ${{ steps.pl.outputs.new-version-4 }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Fetch version
        id: pl
        uses: sanwal-truefoundry/updating-versions@main
        with:
          file-1: 'mlfoundry-server/Chart.yml'
          file-2: 'servicefoundry-server/Chart.yml'
          file-3: 'truefoundry-frontend-app/Chart.yml'
          file-4: 'truefoundry/Chart.yml'
      
      - name: Output results
        run: |
          echo ${{ steps.pl.outputs.new-version-1 }}
          echo ${{ steps.pl.outputs.new-version-2 }}
          echo ${{ steps.pl.outputs.new-version-3 }}
          echo ${{ steps.pl.outputs.new-version-4 }}
      
      - name: Find and Replace MLFoundry Version
        run: |
          sh sed  -i '/version/s/[^.]*$/'"${steps.pl.outputs.new-version-1}\"/" mlfoundry-server/Chart.yml

      
      - name: Find and Replace ServiceFoundry Version
        uses: DamianReeves/write-file-action@master
        with:
          path: servicefoundry-server/Chart.yml
          contents: |
            apiVersion: v2
            name: servicefoundry-server
            version: ${{ steps.pl.outputs.new-version-2 }}
            description: "Servicefoundry-server deployment chart"
            maintainers:
              - name: truefoundry
          write-mode: overwrite

      
      - name: Find and Replace Truefoundry-Frontend-App Version
        uses: DamianReeves/write-file-action@master
        with:
          path: truefoundry-frontend-app/Chart.yml
          contents: |
            apiVersion: v2
            name: truefoundry-frontend-app
            version: ${{ steps.pl.outputs.new-version-3 }}
            description: "Truefoundry-frontend-app deployment chart"
            maintainers:
              - name: truefoundry
          write-mode: overwrite
      
      - name: Comitting the version files
        run: |
           git config user.name github-action
           git add .
           git commit -m "[CI] Update Version"
           git push
  
  print:
    name: Calling Print workflow
    uses: ./.github/workflows/print.yml
    needs: [build]
  
  notify:
    name: Updating Version 2
    needs: [print,build]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Output results
        run: |
          echo ${{ needs.build.outputs.output4 }}

      - name: Find and Replace
        uses: DamianReeves/write-file-action@master
        with:
          path: truefoundry/Chart.yml
          contents: |
            apiVersion: v2
            name: truefoundry
            version: ${{ needs.build.outputs.output4 }}
            description: Truefoundry applications
            maintainers:
              - name: truefoundry
            dependencies:
              - condition: mlfoundry-server.enabled
                name: mlfoundry-server
                repository: https://raw.githubusercontent.com/truefoundry/helm-charts/gh-pages
                version: ${{ needs.build.outputs.output1 }}
              - condition: servicefoundry-server.enabled
                name: servicefoundry-server
                repository: https://raw.githubusercontent.com/truefoundry/helm-charts/gh-pages
                version: ${{ needs.build.outputs.output2 }}
              - condition: truefoundry-frontend-app.enabled
                name: truefoundry-frontend-app
                repository: https://raw.githubusercontent.com/truefoundry/helm-charts/gh-pages
                version: ${{ needs.build.outputs.output3 }}
          write-mode: overwrite
        
      - name: Comitting the file
        run: |
           git config user.name github-action
           git pull
           git add .
           git commit -m "[CI] Update version2.yml"
           git push
