name: Updating Version

on: 
  [workflow_dispatch]

jobs:
  build-container:
    name: Updating Version
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Update version.yml
        uses: fjogeleit/yaml-update-action@main
        with:
          valueFile: 'version.yml'
          propertyPath: 'version'
          value: propertyPath+1
          branch: updating
          targetBranch: updating
          commitChange: 'true'
          updateFile: 'true'
      
      - name: Cat Updated version.yml
        run: cat version.yml