name: Updating Version

on: 
  [workflow_dispatch,push]

jobs:
  build-container:
    name: Updating Version
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: pocket-apps/action-update-version@v1
        with:
          files: 'version.yml'
          version-regexp: '\d'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          branch-name: updating