name: Updating Version

on: workflow_dispatch

jobs:
  build:
    name: Updating Version
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Fetch version
        id: pl
        uses: sanwal-truefoundry/updating-versions@main
        with:
          file: 'version.yml'
      
      - name: Output results
        run: |
          echo ${{ steps.pl.outputs.new-version }}
      
      - name: Update version.yml
        uses: fjogeleit/yaml-update-action@main
        with:
          valueFile: 'version.yml'
          propertyPath: 'version'
          value: ${{ steps.pl.outputs.new-version }}
          branch: main
          targetBranch: main
          commitChange: 'true'
          updateFile: 'true'

  print:
    name: Printing version file
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cat Updated version.yml
        run: cat version.yml
  
  notify:
    name: Updating Version 2
    needs: print
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Output results
        run: |
          echo ${{ needs.build.steps.pl.outputs.new-version }}

      - name: Update version.yml
        uses: fjogeleit/yaml-update-action@main
        with:
          valueFile: 'version2.yml'
          propertyPath: 'dependencies.version'
          value: ${{ needs.build.steps.pl.outputs.new-version }}
          branch: main
          targetBranch: main
          commitChange: 'true'
          updateFile: 'true' 