name: Updating Version

on: 
  [workflow_dispatch,push]

jobs:
  build-container:
    name: Updating Version
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Update version.yml
        uses: fjogeleit/yaml-update-action@main
        with:
          valueFile: 'version.yaml'
          propertyPath: 'version.version'
          value: propertyPath + 1
          commitChange: false
          updateFile: true